### ISSUE TITLE
Absolute linking

### ISSUE THREAD

**Issue by endorama** [mariocasciaro/npm-workspace#13]
Hello and thank for this package!

I've found a behaviour which is in contrast with the documentation.  
The documentation states 

> If a link was specified in workspace.json: creates a local symbolic link (as opposed to npm link that creates a global link) 
> but my module is linked absolutely.

workspace.json:

``` json
{
  "links": {
    "argsify": "./argsify"
  }
}
```

folder structure:

```
.
├── argsify
├── myModule
└── workspace.json
```

node_modules for myModule:

```
$ ls myModule/node_modules
[...] argsify -> /home/.../lib/argsify
[...] lodash
```

Is this expected?

**Comment by mariocasciaro** [comment]
Yes, that's the right behaviour. The documentation talks about local vs global linking (not relative vs absolute paths). `npm link` installs the link in a global directory (e.g. ~/.npm) and then references the link from an installed package, while `npm-workspace` directly references the target package. 
Hope this helps.

**Comment by endorama** [comment]
Thanks for clarification! Would be possible to add relative path linking? If you can point to the right direction I could have a look at it.

**Comment by mariocasciaro** [comment]
Sure it would be possible. May I know what's your use case?
BTW this is the line where links are created https://github.com/mariocasciaro/npm-workspace/blob/master/lib/npm-workspace.js#L305

**Comment by endorama** [comment]
I'm developing a fairly complex app which has a dedicated Vagrant machine setup for development execution.  
As you can guess using absolute linking on my laptop produce paths that do not match with the ones in the Vagrant instance. Relative linking would solve this problem.

It would be possible to just use npm-workspace inside Vagrant, but this adds a point of failure which, if possible, I'd like to avoid. With relative linking you should not care about running npm-workspace on your laptop on in Vagrant, and should always works.

I'll dig in a bit and try to make a PR :) Thanks for your help

**Comment by endorama** [comment]
Closing as very old :)
