### ISSUE TITLE
Globbing support

### ISSUE THREAD

**Issue by awjreynolds** [mariocasciaro/npm-workspace#19]
npm-workspace works at the current directory.

Being able to specify an array of directories would be useful (as well as exclude specific patterns).

Use case:
We release a library, with a set of worked out example installations. We would like npm-workspace to install the example installations which are held in a sub-directory.

**Comment by awjreynolds** [comment]
Just discussed this with a colleague and we felt that "npm-workspace install --recursive" which tells npm-workspace to recurse through all sub folders running npm install (obviously ignoring node_modules directories) would be "good enough".

**Comment by mariocasciaro** [comment]
Hi Adam, thanks for the contribution, it sounds like a reasonable new feature to me. If you have a PR ready I'll merge it for sure, otherwise you'll probably have to wait a bit until I can find the time to work on this.

**Comment by i-e-b** [comment]
I think I should be able to pick this up... expect a PR in a day or so :-)
